"""Shared fixtures for the grader tests.

The grader reads screenshots from directories, so the test fixtures are
committed PNG files under ``tests/fixtures/`` (generated by
``tests/fixtures/_generate.py`` — hand-made solid blocks / simple shapes, fully
deterministic). This fixture just exposes their directory paths.
"""

from pathlib import Path

import pytest

from fixtures import _generate

FIXTURES = Path(__file__).parent / "fixtures"


@pytest.fixture(scope="session")
def fixture_dirs():
    """Directories of committed candidate/reference screenshot fixtures.

    Regenerated on demand so a checkout missing the PNGs still runs; the bytes
    are deterministic, so this is a no-op for a normal checkout.
    """
    if not (FIXTURES / "reference" / "home.png").exists():
        _generate.build()
    return {
        "reference": FIXTURES / "reference",
        "perfect": FIXTURES / "candidate_perfect",
        "blurred": FIXTURES / "candidate_blurred",
        "different": FIXTURES / "candidate_different",
        "multipage": FIXTURES / "candidate_multipage",
    }


@pytest.fixture(scope="session")
def site_dirs():
    """Directories for the live-render grader path (issue 05).

    Candidates are directories of HTML/CSS the grader renders itself; the
    reference is the committed PNG ``site_render_reference/home.png`` rendered
    once from ``site_reference/`` by ``_generate.build_site_reference_png``.
    """
    if not (FIXTURES / "site_render_reference" / "home.png").exists():
        _generate.build_site_reference_png()
    return {
        "reference": FIXTURES / "site_render_reference",
        "perfect": FIXTURES / "site_perfect",
        "wrongcolor": FIXTURES / "site_wrongcolor",
        "missing": FIXTURES / "site_missing",
    }
