"""Shared fixtures for the grader tests.

The grader reads screenshots from directories, so the test fixtures are
committed PNG files under ``tests/fixtures/`` (generated by
``tests/fixtures/_generate.py`` — hand-made solid blocks / simple shapes, fully
deterministic). This fixture just exposes their directory paths.
"""

from pathlib import Path

import pytest

from fixtures import _generate

FIXTURES = Path(__file__).parent / "fixtures"


@pytest.fixture(scope="session")
def fixture_dirs():
    """Directories of committed candidate/reference screenshot fixtures.

    Regenerated on demand so a checkout missing the PNGs still runs; the bytes
    are deterministic, so this is a no-op for a normal checkout.
    """
    if not (FIXTURES / "reference" / "home.png").exists():
        _generate.build()
    return {
        "reference": FIXTURES / "reference",
        "perfect": FIXTURES / "candidate_perfect",
        "blurred": FIXTURES / "candidate_blurred",
        "different": FIXTURES / "candidate_different",
        "multipage": FIXTURES / "candidate_multipage",
    }


PAGE5_MAP = {
    "home": {"screenshot": "home.png", "expected_file": "index.html"},
    "about": {"screenshot": "about.png", "expected_file": "about.html"},
    "services": {"screenshot": "services.png", "expected_file": "services.html"},
    "pricing": {"screenshot": "pricing.png", "expected_file": "pricing.html"},
    "contact": {"screenshot": "contact.png", "expected_file": "contact.html"},
}


@pytest.fixture(scope="session")
def site5(fixture5_reference_images):
    """The committed 5-page reference site plus its rendered reference images.

    ``dir`` is the hand-authored reference site; ``page_map`` is the 5-page map;
    ``reference_images`` is ``{page: PIL.Image}`` rendered once from the site (so
    the study's source-space variants compare apples-to-apples).
    """
    return {
        "dir": FIXTURES / "site5_reference",
        "page_map": PAGE5_MAP,
        "reference_images": fixture5_reference_images,
    }


@pytest.fixture(scope="session")
def fixture5_reference_images():
    """Render the 5-page reference site once and cache the page images."""
    from webdesign_rl.render.browser import render_site

    return render_site(FIXTURES / "site5_reference", PAGE5_MAP)


@pytest.fixture(scope="session")
def site_dirs():
    """Directories for the live-render grader path (issue 05).

    Candidates are directories of HTML/CSS the grader renders itself; the
    reference is the committed PNG ``site_render_reference/home.png`` rendered
    once from ``site_reference/`` by ``_generate.build_site_reference_png``.
    """
    if not (FIXTURES / "site_render_reference" / "home.png").exists():
        _generate.build_site_reference_png()
    return {
        "reference": FIXTURES / "site_render_reference",
        "perfect": FIXTURES / "site_perfect",
        "wrongcolor": FIXTURES / "site_wrongcolor",
        "missing": FIXTURES / "site_missing",
    }
